This should work, with btrfs.
git-svn-id: https://maxwell.derobert.net/svn/DebianLINK@1131 a1ca1053-5dd6-0310-ab23-aaff546d8d42

diff --git a/install-debian b/install-debian
--- a/install-debian
+++ b/install-debian
@@ -27,9 +27,12 @@ cp debconf-seed "$root/root/"
 cp archive-keys "$root/root/"
 cp asound-state "$root/root/"
 chmod +x "$root/root/setup-debian" # just in case
-chroot "$root" /root/setup-debian "$disk"
 
-set +e # go through as many as possible
+set +e # clean up even if setup fails
+if ! chroot "$root" /root/setup-debian "$disk" ; then
+	echo "# SETUP HAS FAILED US. Sending you in to check..."
+	chroot "$root" /bin/bash -i
+fi
 umount "$root/dev/pts"
 umount "$root/dev/shm"
 umount "$root/dev"
